---
# tasks file for cups
- name: Install cups + driver
  apt:
    name: ['cups', 'splix', 'avahi-daemon', 'python3-cups']
    state: present

- name: Render cups config
  template:
    src: cupsd_conf.j2
    dest: /etc/cups/cupsd.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Enable cups
  systemd:
    name: cups
    enabled: yes
    state: restarted
