---
# tasks file for cups
- name: Install cups + driver
  community.general.pacman:
    name: ['cups', 'splix', 'avahi', 'python-pycups']
    state: present

- name: Render cups config
  template:
    src: cupsd_conf.j2
    dest: /etc/cups/cupsd.conf
    owner: root
    group: lp
    mode: '0640'
    backup: yes

- name: Enable cups
  systemd:
    name: cups
    enabled: yes
    state: started
