---
# tasks file for common
- name: Install common tools
  apt:
    name: ['wget', 'htop']
    state: present
    update_cache: yes

- name: Set motd
  template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: '0644'
