---
# tasks file for common
- name: Install common tools
  community.general.pacman:
    name: ['wget', 'htop']
    state: present
    update_cache: yes

- name: Set timezone
  community.general.timezone:
    name: America/New_York

- name: Set motd
  ansible.builtin.template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: '0644'
