---
# tasks file for common
- name: Install common tools
  pacman:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - wget
    - htop

- name: Set timezone
  timezone:
    name: America/New_York

- name: Set motd
  template:
    src: motd.j2
    dest: /etd/motd
    owner: root
    group: root
    mode: '0644'
